name: flutter_nim_example
description: Demonstrates how to use the flutter_nim plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

#  flutter_nim: 0.1.6

  provider: 5.0.0 #√
  shared_preferences: 2.0.5 #√
  cached_network_image: 3.0.0 #√
  audioplayers: 0.18.3 #√
  image_picker: 0.7.4 #√
  permission_handler: 6.1.1 #√
  fluttertoast: 8.0.3 #√
  flutter_keyboard_visibility: 5.0.0 #√
  flutter_easyrefresh: 2.2.1 #√
  sp_util: 2.0.3 #√
  convert: 3.0.0 #√

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_nim:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/default_user_avatar.png
    - images/img_not_available.png

    - images/im_message_cell_error.png
    - images/im_video_play.png
    - images/im_audio_play_left.gif
    - images/im_audio_play_right.gif
    - images/im_audio_stop_left.png
    - images/im_audio_stop_right.png
    - images/im_action_panel_gallery.png
    - images/im_action_panel_camera.png
    - images/im_action_panel_house.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
