name: flutter_nim_example
description: Demonstrates how to use the flutter_nim plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_nim: 0.1.5+1

  provider: 3.1.0+1
  shared_preferences: 0.5.4
  cached_network_image: 1.1.1
  audioplayers: 0.13.2
  image_picker: 0.6.1+8
  permission_handler: 3.3.0
  fluttertoast: 3.1.3
  keyboard_visibility: 0.5.6
  flutter_easyrefresh: 2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_nim:
#    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/default_user_avatar.png
    - images/img_not_available.png

    - images/im_message_cell_error.png
    - images/im_video_play.png
    - images/im_audio_play_left.gif
    - images/im_audio_play_right.gif
    - images/im_audio_stop_left.png
    - images/im_audio_stop_right.png
    - images/im_action_panel_gallery.png
    - images/im_action_panel_camera.png
    - images/im_action_panel_house.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
